services:
  minio:
    hostname: minio
    image: minio/minio:latest
    container_name: minio
    ports:
      # Expose API port 9000 and Console port 9001
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_vol:/data
    # Use environment variables to set root user and password for MinIO
    env_file:
      - .env
    # The command to start the MinIO server and create the console
    command: server /data --console-address ":9001"
    networks:
      - orion_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  python_cleaner:
    build:
      context: .
      dockerfile: Dockerfile_python
    # Mount the local directory to see code changes without rebuilding the image
    env_file:
      - .env
    networks:
      - orion_net
    volumes:
      - ./flatfiles:/app/flatfiles:ro
networks:
  orion_net:
    driver: bridge
volumes:
  minio_vol:
# MinIO service to act as our local S3-compatible object storage

